services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    expose:
      - 27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.stats"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data:
